development:
  adapter: mysql2
  database: vinsol_app_development
  username: root
  password:
  
test:
  adapter: mysql2
  database: vinsol_app_test
  username: root
  password:
  

production:
  adapter: mysql2
  database: vinsol_app_production
  username: root
  password:
